"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
"""
    BASE_DIR aponta para a raiz do projeto (duas pastas acima do arquivo atual). 
    Esse valor é usado para construir caminhos absolutos (por exemplo BASE_DIR / 'static').
    É importante por evita usar os.path e string concatenation, tornando o projeto portável entre OS.
"""
BASE_DIR = Path(__file__).resolve().parent.parent


"""
    SECRET_KEY é um valor sensível usado por Django para criptografia interna 
    (assinatura de cookies, tokens, CSRF, password reset, etc).
    Nunca comitar SECRET_KEY real em repositórios públicos. 
    Em produção, carregue via variável de ambiente ou .env.
"""
SECRET_KEY = 'django-insecure-2qijb05#h(*p^l6^c3yt=d1@qph+(^lbj3uu&cxkgj0kh+(r+p'

"""
    Habilita páginas de erro detalhadas e reload automático. NUNCA deixar True em produção.
"""
DEBUG = True

"""
    ALLOWED_HOSTS é uma lista de hostnames/IPs que Django aceitará nas requisições Host. 
    Em produção deve conter o domínio (ex. ['example.com', 'api.example.com']). 
    Se vazio e DEBUG=False, Django rejeita requisições.
"""
ALLOWED_HOSTS = []


"""
    INSTALLED_APPS lista os apps registrados no projeto
    * django.contrib.* são apps built-in (admin, auth, sessions, etc).
    * rest_framework (DRF) fornece serializadores, views e viewsets para API REST.
    * corsheaders permite configuração de CORS (Cross-Origin Resource Sharing).
    * tasks_app é seu app custom.
    
    OBSERVAÇÃO: Ordem importa em alguns casos (por exemplo, corsheaders.middleware.CorsMiddleware 
    precisa aparecer antes de CommonMiddleware).
"""

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'tasks_app',
]

"""
    MIDDLEWARE são camadas que processam requisições/respostas. Exemplos:
    * CorsMiddleware — adiciona cabeçalhos CORS (permitir que frontend em outro host acesse a API).
    * SecurityMiddleware — adiciona proteções (HSTS, redirecionamento SSL, etc).
    * SessionMiddleware e AuthenticationMiddleware — habilitam sessão e autenticação.
    * CsrfViewMiddleware — proteção CSRF para formulários.

    OBSERVAÇÃO: Ordem importa em alguns casos (por exemplo, corsheaders.middleware.CorsMiddleware 
    precisa aparecer antes de CommonMiddleware).
"""

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

"""
    Indica o módulo onde estão as rotas globais (backend/urls.py).
"""
ROOT_URLCONF = 'backend.urls'

"""
    Configuração de templates (caso use renderização server-side).
    DIRS é onde colocar templates globais (por ex BASE_DIR / 'templates').
    APP_DIRS=True instrui Django a procurar por pastas templates/ dentro de cada app.
"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

"""
    Ponto de entrada WSGI para servidores de produção (Gunicorn, uWSGI). 
    Se usar ASGI (WebSockets), você adicionar ASGI_APPLICATION também.
    Em produção, o servidor chamará backend.wsgi:application.
"""
WSGI_APPLICATION = 'backend.wsgi.application'

"""
    O trecho comentado mostra a configuração padrão SQLite (boa para dev rápido).
"""
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

"""
    Configuração comentada usa PostgreSQL com credenciais postgres/postgres e host localhost.
    
    OBSERVAÇÃO: Atenção com Docker: se você estiver executando PostgreSQL em um container pelo docker-compose 
    cujo serviço se chama db, o HOST dentro do container Django deve ser db (o nome do serviço), não localhost. 
    Se Django roda localmente e Postgres no container, localhost pode funcionar (via porta mapeada), 
    mas para containers intercomunicarem use o serviço name.
"""
#DATABASES = {
#        'default': {
#            'ENGINE': 'django.db.backends.postgresql',
#            'NAME': 'postgres',
#            'USER': 'postgres',
#            'PASSWORD': 'postgres',
#            'HOST': 'localhost',
#            'PORT': '5432',
#        }
#    }

"""
    Configuração ativa usa PostgreSQL com credenciais postgres/postgres e host localhost, de modo similar ao trecho
    anterior, contudo aqui é permitida a configuração per-environment sem mudar código.
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


"""
    Conjunto de validadores que reforçam a força das senhas.
    Mantê-los ativos é boa prática em produção.
"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

"""
    * LANGUAGE_CODE define o idioma padrão.
    * TIME_ZONE = 'UTC' — bom padrão; porém se você quiser timestamps no fuso local pode usar 'America/Sao_Paulo'.
    * USE_TZ = True habilita uso de timezone-aware datetimes (recomendado).
    * Observação: se você setar TIME_ZONE='America/Sao_Paulo', Django armazena datetimes em UTC no DB e converte 
                para o timezone ao mostrar dependendo do settings/context.
"""
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
"""
    URL onde arquivos estáticos serão servidos 
    (em dev Django já serve, em produção geralmente usa-se servidor web ou whitenoise).
"""
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

"""
    Define o tipo de campo auto-incremento para modelos que não declaram id. 
    BigAutoField usa inteiros maiores (seguro para grandes tabelas).
"""
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
    permite que qualquer origem (qualquer domínio) acesse a sua API. É conveniente em desenvolvimento mas muito inseguro em produção.
    Recomendação: em produção, definir origens permitidas explicitamente, por exemplo:
        CORS_ALLOW_ALL_ORIGINS = False
        CORS_ALLOWED_ORIGINS = [
            "https://seusite.com",
            "https://app.seusite.com",
        ]
"""
CORS_ALLOW_ALL_ORIGINS = True
